Update Install

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -50,4 +50,42 @@ echo "Select an option"
 echo "1) Install boxvidra with box86 build (6 June)"
 echo "2) Install boxvidra with wow64 build (Complete version)"
 echo ""
-echo -n "Selected number: "
+echo -n "Selected number:
+
+
+echo "Installing mobox"
+
+function wget-git-q {
+    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
+    return $?
+}
+
+echo "Updating package manager"
+mkdir -p $PREFIX/glibc/opt/package-manager/installed
+
+if [ "$INSTALL_WOW64" = "1" ]; then
+echo "PRIVATE_TOKEN=glpat-h5r7HjKoPKZPxmfg79xs
+PROJECT_ID=54240888">$PREFIX/glibc/opt/package-manager/token
+else
+echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
+PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
+fi
+
+. $PREFIX/glibc/opt/package-manager/token
+if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
+    echo "Download failed"
+    return 1
+fi
+. $PREFIX/glibc/opt/package-manager/package-manager
+sync-all
+
+if [ "$INSTALL_WOW64" = "1" ]; then
+sync-package wine-9.3-vanilla-wow64
+else
+sync-package wine-ge-custom-8-25
+fi
+
+ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/mobox
+echo "To start - type \"box32droid\""
+
+
